name: run-tests-and-report-coverage

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  assemble-release:
    name: Run tests & report coverage
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        working-directory: ./app
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test
