name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-demos:
    name: Build demos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci --legacy-peer-deps

      - name: Build plugin bundles
        run: npm run build

      - name: Build demos
        run: npm run build:demos

      - name: Upload demos artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: demos/dist

  publish-demos:
    name: Publish demos
    runs-on: ubuntu-latest
    needs: build-demos
    environment:
      name: github-pages
      url: ${{ steps.publishing.outputs.page_url }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Publish demos to GH Pages
        id: publishing
        uses: actions/deploy-pages@v4
